# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8542181468ee771871cbea655f6466ff7dff8b02f1803bca1b5d71edc7fba5823336570a6e3f9ea06f06968a044187319710dc593b847f69ecb05f820cee8c60

test:
  secret_key_base: 17169f1942f8bdcab5c09986e86869651a62b3ce82c157616a0a4455eee395656843f4ade368c22b02d591769485bebf19d17616863c14f3595d58310910eaf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
